package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const generatedSuffix = "_acceptance_test.go"

var nonIdent = regexp.MustCompile(`[^A-Za-z0-9_]`)

const testTemplate = `// Code generated by acceptance-entrypoint-generator; DO NOT EDIT.
package generated

import (
	"testing"

	"github.com/masonhuemmer/m365/acceptance/runtime"
	_ "github.com/masonhuemmer/m365/acceptance/steps"
)

func TestAcceptance_%s(t *testing.T) {
	runtime.RunFeature(t, %q)
}
`

// feature is one feature file and the test name generated for it.
type feature struct {
	Name, Path string
}

// generate writes one acceptance test per feature under root into outDir.
// The new set is written to a staging folder first; only when every file
// is written are the old generated tests removed and the new ones moved
// in. A name clash is an error and leaves outDir untouched.
func generate(root, outDir string) error {
	features, err := listFeatures(root)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return err
	}
	stage, err := os.MkdirTemp(filepath.Dir(outDir), ".acceptance-generated-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)
	for _, f := range features {
		rel, err := filepath.Rel(outDir, f.Path)
		if err != nil {
			return err
		}
		src := fmt.Sprintf(testTemplate, f.Name, filepath.ToSlash(rel))
		if err := os.WriteFile(filepath.Join(stage, f.Name+generatedSuffix), []byte(src), 0o600); err != nil {
			return err
		}
	}
	if err := removeGenerated(outDir); err != nil {
		return err
	}
	for _, f := range features {
		name := f.Name + generatedSuffix
		if err := os.Rename(filepath.Join(stage, name), filepath.Join(outDir, name)); err != nil {
			return err
		}
	}
	return nil
}

// listFeatures returns every feature under root with its test name, sorted
// by name. It is the one list both the generator and acceptance.sh use.
// Names come from the path under root (cli/help.feature -> cli_help); two
// features whose names match ignoring case are an error, because their
// files would collide on a case-insensitive disk.
func listFeatures(root string) ([]feature, error) {
	var out []feature
	seen := map[string]string{}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".feature") {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		name := nonIdent.ReplaceAllString(strings.TrimSuffix(rel, ".feature"), "_")
		key := strings.ToLower(name)
		if prev, ok := seen[key]; ok {
			return fmt.Errorf("features %s and %s both map to test name %s (ignoring case); rename one", prev, rel, name)
		}
		seen[key] = rel
		out = append(out, feature{Name: name, Path: path})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

func removeGenerated(outDir string) error {
	old, err := filepath.Glob(filepath.Join(outDir, "*"+generatedSuffix))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	return nil
}
