package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// layout creates files (path -> content) under a temp dir and returns it.
func layout(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for p, c := range files {
		full := filepath.Join(dir, p)
		if err := os.MkdirAll(filepath.Dir(full), 0o750); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(c), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func generated(t *testing.T, outDir string) []string {
	t.Helper()
	entries, err := os.ReadDir(outDir)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	sort.Strings(names)
	return names
}

func TestGenerateNamesTestsByPath(t *testing.T) {
	dir := layout(t, map[string]string{
		"features/cli/help.feature":        "Feature: cli help\n",
		"features/mcp/help.feature":        "Feature: mcp help\n",
		"features/mail/send-reply.feature": "Feature: send\n",
	})
	out := filepath.Join(dir, "acceptance", "generated")
	if err := generate(filepath.Join(dir, "features"), out); err != nil {
		t.Fatal(err)
	}
	want := []string{
		"cli_help_acceptance_test.go",
		"mail_send_reply_acceptance_test.go",
		"mcp_help_acceptance_test.go",
	}
	if got := generated(t, out); strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("files %v want %v", got, want)
	}
	src, err := os.ReadFile(filepath.Join(out, "cli_help_acceptance_test.go"))
	if err != nil {
		t.Fatal(err)
	}
	wantSrc := `// Code generated by acceptance-entrypoint-generator; DO NOT EDIT.
package generated

import (
	"testing"

	"github.com/masonhuemmer/m365/acceptance/runtime"
	_ "github.com/masonhuemmer/m365/acceptance/steps"
)

func TestAcceptance_cli_help(t *testing.T) {
	runtime.RunFeature(t, "../../features/cli/help.feature")
}
`
	if string(src) != wantSrc {
		t.Fatalf("generated\n%s\nwant\n%s", src, wantSrc)
	}
}

func TestGenerateRemovesStaleTests(t *testing.T) {
	dir := layout(t, map[string]string{
		"features/cli/help.feature":                    "Feature: cli help\n",
		"acceptance/generated/old_acceptance_test.go":  "package generated\n",
		"acceptance/generated/help_acceptance_test.go": "package generated\n",
		"acceptance/generated/keep.txt":                "not generated\n",
	})
	out := filepath.Join(dir, "acceptance", "generated")
	if err := generate(filepath.Join(dir, "features"), out); err != nil {
		t.Fatal(err)
	}
	want := []string{"cli_help_acceptance_test.go", "keep.txt"}
	if got := generated(t, out); strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("files %v want %v", got, want)
	}
}

func TestGenerateFailsOnNameClash(t *testing.T) {
	dir := layout(t, map[string]string{
		"features/mail/send-reply.feature": "Feature: a\n",
		"features/mail/send_reply.feature": "Feature: b\n",
		"acceptance/generated/keep.txt":    "not generated\n",
	})
	out := filepath.Join(dir, "acceptance", "generated")
	err := generate(filepath.Join(dir, "features"), out)
	if err == nil {
		t.Fatal("want an error for two features with the same test name")
	}
	for _, want := range []string{"mail_send_reply", "mail/send-reply.feature", "mail/send_reply.feature"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("error %q lacks %q", err, want)
		}
	}
	if got := generated(t, out); strings.Join(got, ",") != "keep.txt" {
		t.Fatalf("a clash must write nothing; files %v", got)
	}
}

func TestGenerateReportsMissingRoot(t *testing.T) {
	dir := t.TempDir()
	if err := generate(filepath.Join(dir, "features"), filepath.Join(dir, "out")); err == nil {
		t.Fatal("want an error for a missing features directory")
	}
}
