package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const generatedSuffix = "_acceptance_test.go"

var nonIdent = regexp.MustCompile(`[^A-Za-z0-9_]`)

const testTemplate = `// Code generated by acceptance-entrypoint-generator; DO NOT EDIT.
package generated

import (
	"testing"

	"github.com/masonhuemmer/m365/acceptance/runtime"
	_ "github.com/masonhuemmer/m365/acceptance/steps"
)

func TestAcceptance_%s(t *testing.T) {
	runtime.RunFeature(t, %q)
}
`

// generate writes one acceptance test per feature file under root into
// outDir. Names come from the feature's path under root (cli/help.feature
// -> cli_help), so features with the same file name in different folders
// both run. Stale generated tests are removed first; two features that map
// to the same name are an error and nothing is written.
func generate(root, outDir string) error {
	names, err := featureNames(root)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return err
	}
	if err := removeGenerated(outDir); err != nil {
		return err
	}
	keys := make([]string, 0, len(names))
	for name := range names {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	for _, name := range keys {
		rel, err := filepath.Rel(outDir, names[name])
		if err != nil {
			return err
		}
		src := fmt.Sprintf(testTemplate, name, filepath.ToSlash(rel))
		if err := os.WriteFile(filepath.Join(outDir, name+generatedSuffix), []byte(src), 0o600); err != nil {
			return err
		}
	}
	return nil
}

// featureNames maps each test name to its feature file, failing on a clash.
func featureNames(root string) (map[string]string, error) {
	names := map[string]string{}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".feature") {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		name := nonIdent.ReplaceAllString(strings.TrimSuffix(filepath.ToSlash(rel), ".feature"), "_")
		if prev, ok := names[name]; ok {
			return fmt.Errorf("features %s and %s both map to test name %s; rename one",
				filepath.ToSlash(mustRel(root, prev)), filepath.ToSlash(rel), name)
		}
		names[name] = path
		return nil
	})
	return names, err
}

func removeGenerated(outDir string) error {
	old, err := filepath.Glob(filepath.Join(outDir, "*"+generatedSuffix))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	return nil
}

func mustRel(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return rel
}
