package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := "features"
	outDir := "acceptance/generated"
	_ = os.MkdirAll(outDir, 0o750)
	_ = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".feature") {
			return err
		}
		base := strings.TrimSuffix(filepath.Base(path), ".feature")
		rel, _ := filepath.Rel(".", path)
		feat := filepath.ToSlash(filepath.Join("..", "..", rel))
		src := fmt.Sprintf(`// Code generated by acceptance-entrypoint-generator; DO NOT EDIT.
package generated

import (
	"testing"

	"github.com/masonhuemmer/m365/acceptance/runtime"
	_ "github.com/masonhuemmer/m365/acceptance/steps"
)

func TestAcceptance_%s(t *testing.T) {
	runtime.RunFeature(t, %q)
}
`, strings.ReplaceAll(base, "-", "_"), feat)
		_ = os.WriteFile(filepath.Join(outDir, base+"_acceptance_test.go"), []byte(src), 0o600)
		return nil
	})
}
