# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class M365 < Formula
  desc "Microsoft 365 CLI for one signed-in user"
  homepage "https://github.com/jacobhuemmer/m365"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.0/m365_0.1.0_darwin_amd64.tar.gz"
      sha256 "9e143015b7e0c1d9b677c6696f41116b915d0932bbe2cbff80f4e97dd51679b8"

      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.0/m365_0.1.0_darwin_arm64.tar.gz"
      sha256 "a321a1e0f6a959d13dd71c24240b08b4f87e1e8317380a86da83731eb1eceddc"

      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.0/m365_0.1.0_linux_amd64.tar.gz"
      sha256 "42cd23fca5d015a7bfa63a2aae9c90e67f69586aee49e2f52a0e208c3381709e"
      define_method(:install) do
        bin.install "m365"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jacobhuemmer/m365/releases/download/v0.1.0/m365_0.1.0_linux_arm64.tar.gz"
      sha256 "c14c7f4cd4d63f281a199b146000fc4e7f7a96e945a03c398886944c169c5f15"
      define_method(:install) do
        bin.install "m365"
      end
    end
  end

  head "https://github.com/jacobhuemmer/m365.git", branch: "main"

  test do
    assert_match "m365", shell_output("#{bin}/m365 --help")
    assert_match version.to_s, shell_output("#{bin}/m365 --version")
  end
end
